// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: guest/guest.proto

package guest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GuestAgent_Exec_FullMethodName      = "/guest.GuestAgent/Exec"
	GuestAgent_HTTPCheck_FullMethodName = "/guest.GuestAgent/HTTPCheck"
	GuestAgent_Metrics_FullMethodName   = "/guest.GuestAgent/Metrics"
)

// GuestAgentClient is the client API for GuestAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuestAgentClient interface {
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	HTTPCheck(ctx context.Context, in *HTTPCheckRequest, opts ...grpc.CallOption) (*HTTPCheckResponse, error)
	Metrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
}

type guestAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewGuestAgentClient(cc grpc.ClientConnInterface) GuestAgentClient {
	return &guestAgentClient{cc}
}

func (c *guestAgentClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, GuestAgent_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestAgentClient) HTTPCheck(ctx context.Context, in *HTTPCheckRequest, opts ...grpc.CallOption) (*HTTPCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HTTPCheckResponse)
	err := c.cc.Invoke(ctx, GuestAgent_HTTPCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestAgentClient) Metrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, GuestAgent_Metrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuestAgentServer is the server API for GuestAgent service.
// All implementations must embed UnimplementedGuestAgentServer
// for forward compatibility.
type GuestAgentServer interface {
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	HTTPCheck(context.Context, *HTTPCheckRequest) (*HTTPCheckResponse, error)
	Metrics(context.Context, *MetricsRequest) (*MetricsResponse, error)
	mustEmbedUnimplementedGuestAgentServer()
}

// UnimplementedGuestAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuestAgentServer struct{}

func (UnimplementedGuestAgentServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedGuestAgentServer) HTTPCheck(context.Context, *HTTPCheckRequest) (*HTTPCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HTTPCheck not implemented")
}
func (UnimplementedGuestAgentServer) Metrics(context.Context, *MetricsRequest) (*MetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Metrics not implemented")
}
func (UnimplementedGuestAgentServer) mustEmbedUnimplementedGuestAgentServer() {}
func (UnimplementedGuestAgentServer) testEmbeddedByValue()                    {}

// UnsafeGuestAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuestAgentServer will
// result in compilation errors.
type UnsafeGuestAgentServer interface {
	mustEmbedUnimplementedGuestAgentServer()
}

func RegisterGuestAgentServer(s grpc.ServiceRegistrar, srv GuestAgentServer) {
	// If the following call panics, it indicates UnimplementedGuestAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GuestAgent_ServiceDesc, srv)
}

func _GuestAgent_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestAgent_HTTPCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).HTTPCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_HTTPCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).HTTPCheck(ctx, req.(*HTTPCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestAgent_Metrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).Metrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_Metrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).Metrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuestAgent_ServiceDesc is the grpc.ServiceDesc for GuestAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuestAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "guest.GuestAgent",
	HandlerType: (*GuestAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exec",
			Handler:    _GuestAgent_Exec_Handler,
		},
		{
			MethodName: "HTTPCheck",
			Handler:    _GuestAgent_HTTPCheck_Handler,
		},
		{
			MethodName: "Metrics",
			Handler:    _GuestAgent_Metrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guest/guest.proto",
}
