// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: guest/guest.proto

package guest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        []string               `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_guest_guest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_guest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_guest_guest_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_guest_guest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guest_guest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_guest_guest_proto_rawDescGZIP(), []int{1}
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type HTTPCheckRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Port           int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Path           string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers        map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HTTPCheckRequest) Reset() {
	*x = HTTPCheckRequest{}
	mi := &file_guest_guest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPCheckRequest) ProtoMessage() {}

func (x *HTTPCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_guest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPCheckRequest.ProtoReflect.Descriptor instead.
func (*HTTPCheckRequest) Descriptor() ([]byte, []int) {
	return file_guest_guest_proto_rawDescGZIP(), []int{2}
}

func (x *HTTPCheckRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HTTPCheckRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPCheckRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPCheckRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type HTTPCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPCheckResponse) Reset() {
	*x = HTTPCheckResponse{}
	mi := &file_guest_guest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPCheckResponse) ProtoMessage() {}

func (x *HTTPCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guest_guest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPCheckResponse.ProtoReflect.Descriptor instead.
func (*HTTPCheckResponse) Descriptor() ([]byte, []int) {
	return file_guest_guest_proto_rawDescGZIP(), []int{3}
}

func (x *HTTPCheckResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_guest_guest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guest_guest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_guest_guest_proto_rawDescGZIP(), []int{4}
}

type MetricsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuUsageRatio   float64                `protobuf:"fixed64,1,opt,name=cpu_usage_ratio,json=cpuUsageRatio,proto3" json:"cpu_usage_ratio,omitempty"`
	MemoryUsedBytes int64                  `protobuf:"varint,2,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	DiskUsedBytes   int64                  `protobuf:"varint,3,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_guest_guest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guest_guest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_guest_guest_proto_rawDescGZIP(), []int{5}
}

func (x *MetricsResponse) GetCpuUsageRatio() float64 {
	if x != nil {
		return x.CpuUsageRatio
	}
	return 0
}

func (x *MetricsResponse) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *MetricsResponse) GetDiskUsedBytes() int64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

var File_guest_guest_proto protoreflect.FileDescriptor

const file_guest_guest_proto_rawDesc = "" +
	"\n" +
	"\x11guest/guest.proto\x12\x05guest\"P\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\"[\n" +
	"\fExecResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\"\xdf\x01\n" +
	"\x10HTTPCheckRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12>\n" +
	"\aheaders\x18\x03 \x03(\v2$.guest.HTTPCheckRequest.HeadersEntryR\aheaders\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x11HTTPCheckResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\"\x10\n" +
	"\x0eMetricsRequest\"\x8d\x01\n" +
	"\x0fMetricsResponse\x12&\n" +
	"\x0fcpu_usage_ratio\x18\x01 \x01(\x01R\rcpuUsageRatio\x12*\n" +
	"\x11memory_used_bytes\x18\x02 \x01(\x03R\x0fmemoryUsedBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x03 \x01(\x03R\rdiskUsedBytes2\xb7\x01\n" +
	"\n" +
	"GuestAgent\x12/\n" +
	"\x04Exec\x12\x12.guest.ExecRequest\x1a\x13.guest.ExecResponse\x12>\n" +
	"\tHTTPCheck\x12\x17.guest.HTTPCheckRequest\x1a\x18.guest.HTTPCheckResponse\x128\n" +
	"\aMetrics\x12\x15.guest.MetricsRequest\x1a\x16.guest.MetricsResponseBn\n" +
	"\tcom.guestB\n" +
	"GuestProtoP\x01Z!github.com/syscode-labs/imp/guest\xa2\x02\x03GXX\xaa\x02\x05Guest\xca\x02\x05Guest\xe2\x02\x11Guest\\GPBMetadata\xea\x02\x05Guestb\x06proto3"

var (
	file_guest_guest_proto_rawDescOnce sync.Once
	file_guest_guest_proto_rawDescData []byte
)

func file_guest_guest_proto_rawDescGZIP() []byte {
	file_guest_guest_proto_rawDescOnce.Do(func() {
		file_guest_guest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guest_guest_proto_rawDesc), len(file_guest_guest_proto_rawDesc)))
	})
	return file_guest_guest_proto_rawDescData
}

var file_guest_guest_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_guest_guest_proto_goTypes = []any{
	(*ExecRequest)(nil),       // 0: guest.ExecRequest
	(*ExecResponse)(nil),      // 1: guest.ExecResponse
	(*HTTPCheckRequest)(nil),  // 2: guest.HTTPCheckRequest
	(*HTTPCheckResponse)(nil), // 3: guest.HTTPCheckResponse
	(*MetricsRequest)(nil),    // 4: guest.MetricsRequest
	(*MetricsResponse)(nil),   // 5: guest.MetricsResponse
	nil,                       // 6: guest.HTTPCheckRequest.HeadersEntry
}
var file_guest_guest_proto_depIdxs = []int32{
	6, // 0: guest.HTTPCheckRequest.headers:type_name -> guest.HTTPCheckRequest.HeadersEntry
	0, // 1: guest.GuestAgent.Exec:input_type -> guest.ExecRequest
	2, // 2: guest.GuestAgent.HTTPCheck:input_type -> guest.HTTPCheckRequest
	4, // 3: guest.GuestAgent.Metrics:input_type -> guest.MetricsRequest
	1, // 4: guest.GuestAgent.Exec:output_type -> guest.ExecResponse
	3, // 5: guest.GuestAgent.HTTPCheck:output_type -> guest.HTTPCheckResponse
	5, // 6: guest.GuestAgent.Metrics:output_type -> guest.MetricsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_guest_guest_proto_init() }
func file_guest_guest_proto_init() {
	if File_guest_guest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guest_guest_proto_rawDesc), len(file_guest_guest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guest_guest_proto_goTypes,
		DependencyIndexes: file_guest_guest_proto_depIdxs,
		MessageInfos:      file_guest_guest_proto_msgTypes,
	}.Build()
	File_guest_guest_proto = out.File
	file_guest_guest_proto_goTypes = nil
	file_guest_guest_proto_depIdxs = nil
}
