{{- if and (default true .Values.webhook.enabled) .Values.webhook.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "imp.fullname" . }}-webhook-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imp.labels" . | nindent 4 }}
spec:
  secretName: {{ include "imp.fullname" . }}-webhook-tls
  duration: {{ .Values.webhook.certManager.duration }}
  renewBefore: {{ .Values.webhook.certManager.renewBefore }}
  dnsNames:
    - {{ include "imp.fullname" . }}-operator.{{ .Release.Namespace }}.svc
    - {{ include "imp.fullname" . }}-operator.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    {{- if .Values.webhook.certManager.issuerRef.name }}
    {{- toYaml .Values.webhook.certManager.issuerRef | nindent 4 }}
    {{- else }}
    name: {{ include "imp.fullname" . }}-selfsigned
    kind: Issuer
    group: cert-manager.io
    {{- end }}
{{- end }}
