{{- if .Values.webhook.certManager.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "imp.fullname" . }}-validating-webhooks
  labels:
    {{- include "imp.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "imp.fullname" . }}-webhook-tls
webhooks:
- name: vimpvm.kb.io
  admissionReviewVersions: ["v1"]
  clientConfig:
    service:
      name: {{ include "imp.fullname" . }}-operator
      namespace: {{ .Release.Namespace }}
      port: 9443
      path: /validate-imp-dev-v1alpha1-impvm
  rules:
  - apiGroups: ["imp.dev"]
    apiVersions: ["v1alpha1"]
    operations:
      - CREATE
      - UPDATE
    resources: [impvms]
    scope: Namespaced
  failurePolicy: Fail
  sideEffects: None
- name: vimpvmclass.kb.io
  admissionReviewVersions: ["v1"]
  clientConfig:
    service:
      name: {{ include "imp.fullname" . }}-operator
      namespace: {{ .Release.Namespace }}
      port: 9443
      path: /validate-imp-dev-v1alpha1-impvmclass
  rules:
  - apiGroups: ["imp.dev"]
    apiVersions: ["v1alpha1"]
    operations:
      - CREATE
      - UPDATE
    resources: [impvmclasses]
    scope: Cluster
  failurePolicy: Fail
  sideEffects: None
- name: vimpvmtemplate.kb.io
  admissionReviewVersions: ["v1"]
  clientConfig:
    service:
      name: {{ include "imp.fullname" . }}-operator
      namespace: {{ .Release.Namespace }}
      port: 9443
      path: /validate-imp-dev-v1alpha1-impvmtemplate
  rules:
  - apiGroups: ["imp.dev"]
    apiVersions: ["v1alpha1"]
    operations:
      - CREATE
      - UPDATE
    resources: [impvmtemplates]
    scope: Namespaced
  failurePolicy: Fail
  sideEffects: None
{{- end }}
