apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "impsandbox.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "impsandbox.labels" . | nindent 4 }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.imagePullSecrets | nindent 2 }}
{{- end }}
