apiVersion: v1
kind: Service
metadata:
  name: {{ include "impsandbox.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "impsandbox.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "impsandbox.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  ports:
  - name: webhook
    port: 9443
    targetPort: webhook
