# syntax=docker/dockerfile:1
FROM golang:1.23-alpine AS builder
WORKDIR /workspace

COPY go.mod go.sum ./
RUN go mod download

COPY api/ api/
COPY cmd/agent/ cmd/agent/
COPY internal/ internal/

RUN CGO_ENABLED=0 GOOS=linux go build -a -o agent ./cmd/agent

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/agent .
USER 65532:65532
ENTRYPOINT ["/agent"]
