apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "imp.fullname" . }}-operator
  labels:
    {{- include "imp.labels" . | nindent 4 }}
rules:
- apiGroups: ["imp.dev"]
  resources:
    - impvms
    - impvmclasses
    - impvmtemplates
    - impnetworks
    - clusterimpconfigs
    - clusterimpnodeprofiles
    - impvmsnapshots
    - impwarmpools
    - impvmmigrations
    - impvmrunnerpools
  verbs: [get, list, watch, create, update, patch, delete]
- apiGroups: ["imp.dev"]
  resources:
    - impvms/status
    - impnetworks/status
    - impvmsnapshots/status
    - impwarmpools/status
    - impvmmigrations/status
    - impvmrunnerpools/status
  verbs: [get, update, patch]
- apiGroups: ["imp.dev"]
  resources:
    - impvms/finalizers
    - impnetworks/finalizers
    - impvmsnapshots/finalizers
    - impwarmpools/finalizers
    - impvmmigrations/finalizers
  verbs: [update]
- apiGroups: [""]
  resources: [nodes]
  verbs: [get, list, watch]
- apiGroups: [""]
  resources: [events]
  verbs: [create, patch]
- apiGroups: [""]
  resources: [secrets]
  verbs: [get]
- apiGroups: ["apiextensions.k8s.io"]
  resources: [customresourcedefinitions]
  verbs: [get, list]
