---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - cilium.io
  resources:
  - ciliumexternalworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imp.dev
  resources:
  - clusterimpconfigs
  - clusterimpnodeprofiles
  - impvmtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - imp.dev
  resources:
  - impnetworks
  - impvmmigrations
  - impvmrunnerpools
  - impvms
  - impvmsnapshots
  - impwarmpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imp.dev
  resources:
  - impnetworks/finalizers
  - impvmmigrations/finalizers
  - impvms/finalizers
  - impvmsnapshots/finalizers
  - impwarmpools/finalizers
  verbs:
  - update
- apiGroups:
  - imp.dev
  resources:
  - impnetworks/status
  - impvmmigrations/status
  - impvmrunnerpools/status
  - impvms/status
  - impvmsnapshots/status
  - impwarmpools/status
  verbs:
  - get
  - patch
  - update
