---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - imp.dev
  resources:
  - clusterimpconfigs
  - clusterimpnodeprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - imp.dev
  resources:
  - impvms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imp.dev
  resources:
  - impvms/finalizers
  verbs:
  - update
- apiGroups:
  - imp.dev
  resources:
  - impvms/status
  verbs:
  - get
  - patch
  - update
