apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "imp.fullname" . }}-agent
  labels:
    {{- include "imp.labels" . | nindent 4 }}
rules:
- apiGroups: ["imp.dev"]
  resources: [impvms]
  verbs: [get, list, watch, update, patch]
- apiGroups: ["imp.dev"]
  resources: [impvms/status]
  verbs: [get, update, patch]
- apiGroups: ["imp.dev"]
  resources: [impvmclasses]
  verbs: [get]
- apiGroups: ["imp.dev"]
  resources: [impnetworks]
  verbs: [get]
- apiGroups: [""]
  resources: [events]
  verbs: [create, patch]
