// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sandboxgateway/gateway.proto

// Package sandboxgateway defines the node-local data-plane gateway service.
// The gateway authenticates callers via per-sandbox HMAC bearer tokens and
// proxies calls to the guest SandboxControl service over the VM's VSOCK
// unix socket.

package sandboxgateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VMRef identifies the target sandbox's backing VM. Namespace + VM name map
// 1:1 onto the node-local socket convention.
type VMRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	VmName        string                 `protobuf:"bytes,2,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMRef) Reset() {
	*x = VMRef{}
	mi := &file_sandboxgateway_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMRef) ProtoMessage() {}

func (x *VMRef) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxgateway_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMRef.ProtoReflect.Descriptor instead.
func (*VMRef) Descriptor() ([]byte, []int) {
	return file_sandboxgateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *VMRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *VMRef) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

type ExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Vm             *VMRef                 `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	Command        []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_sandboxgateway_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxgateway_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_sandboxgateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *ExecRequest) GetVm() *VMRef {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *ExecRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// ExecFrame carries incremental output; the terminal frame sets final=true
// with exit_code.
type ExecFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecFrame_Stdout
	//	*ExecFrame_Stderr
	Payload       isExecFrame_Payload `protobuf_oneof:"payload"`
	ExitCode      int32               `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Final         bool                `protobuf:"varint,4,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecFrame) Reset() {
	*x = ExecFrame{}
	mi := &file_sandboxgateway_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecFrame) ProtoMessage() {}

func (x *ExecFrame) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxgateway_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecFrame.ProtoReflect.Descriptor instead.
func (*ExecFrame) Descriptor() ([]byte, []int) {
	return file_sandboxgateway_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ExecFrame) GetPayload() isExecFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecFrame) GetStdout() string {
	if x != nil {
		if x, ok := x.Payload.(*ExecFrame_Stdout); ok {
			return x.Stdout
		}
	}
	return ""
}

func (x *ExecFrame) GetStderr() string {
	if x != nil {
		if x, ok := x.Payload.(*ExecFrame_Stderr); ok {
			return x.Stderr
		}
	}
	return ""
}

func (x *ExecFrame) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecFrame) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type isExecFrame_Payload interface {
	isExecFrame_Payload()
}

type ExecFrame_Stdout struct {
	Stdout string `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecFrame_Stderr struct {
	Stderr string `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

func (*ExecFrame_Stdout) isExecFrame_Payload() {}

func (*ExecFrame_Stderr) isExecFrame_Payload() {}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VMRef                 `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_sandboxgateway_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxgateway_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_sandboxgateway_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ReadFileRequest) GetVm() *VMRef {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Truncated     bool                   `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_sandboxgateway_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxgateway_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_sandboxgateway_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ReadFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ReadFileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ReadFileResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VMRef                 `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Append        bool                   `protobuf:"varint,4,opt,name=append,proto3" json:"append,omitempty"`
	Mode          int32                  `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_sandboxgateway_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxgateway_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_sandboxgateway_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *WriteFileRequest) GetVm() *VMRef {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WriteFileRequest) GetAppend() bool {
	if x != nil {
		return x.Append
	}
	return false
}

func (x *WriteFileRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_sandboxgateway_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxgateway_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_sandboxgateway_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *WriteFileResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VMRef                 `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_sandboxgateway_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxgateway_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_sandboxgateway_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *ListDirRequest) GetVm() *VMRef {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*GuestFileEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_sandboxgateway_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxgateway_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_sandboxgateway_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *ListDirResponse) GetEntries() []*GuestFileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GuestFileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	IsDir         bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	ModifiedUnix  int64                  `protobuf:"varint,4,opt,name=modified_unix,json=modifiedUnix,proto3" json:"modified_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestFileEntry) Reset() {
	*x = GuestFileEntry{}
	mi := &file_sandboxgateway_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestFileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestFileEntry) ProtoMessage() {}

func (x *GuestFileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxgateway_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestFileEntry.ProtoReflect.Descriptor instead.
func (*GuestFileEntry) Descriptor() ([]byte, []int) {
	return file_sandboxgateway_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *GuestFileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuestFileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GuestFileEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *GuestFileEntry) GetModifiedUnix() int64 {
	if x != nil {
		return x.ModifiedUnix
	}
	return 0
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VMRef                 `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_sandboxgateway_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxgateway_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_sandboxgateway_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *StatRequest) GetVm() *VMRef {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	ModifiedUnix  int64                  `protobuf:"varint,3,opt,name=modified_unix,json=modifiedUnix,proto3" json:"modified_unix,omitempty"`
	Mode          int32                  `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_sandboxgateway_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxgateway_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_sandboxgateway_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *StatResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StatResponse) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *StatResponse) GetModifiedUnix() int64 {
	if x != nil {
		return x.ModifiedUnix
	}
	return 0
}

func (x *StatResponse) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VMRef                 `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_sandboxgateway_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxgateway_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_sandboxgateway_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveRequest) GetVm() *VMRef {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *RemoveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoveRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_sandboxgateway_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandboxgateway_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_sandboxgateway_gateway_proto_rawDescGZIP(), []int{13}
}

var File_sandboxgateway_gateway_proto protoreflect.FileDescriptor

const file_sandboxgateway_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1csandboxgateway/gateway.proto\x12\x0esandboxgateway\">\n" +
	"\x05VMRef\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x17\n" +
	"\avm_name\x18\x02 \x01(\tR\x06vmName\"w\n" +
	"\vExecRequest\x12%\n" +
	"\x02vm\x18\x01 \x01(\v2\x15.sandboxgateway.VMRefR\x02vm\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"}\n" +
	"\tExecFrame\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\tH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\tH\x00R\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05final\x18\x04 \x01(\bR\x05finalB\t\n" +
	"\apayload\"L\n" +
	"\x0fReadFileRequest\x12%\n" +
	"\x02vm\x18\x01 \x01(\v2\x15.sandboxgateway.VMRefR\x02vm\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"^\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\"\x93\x01\n" +
	"\x10WriteFileRequest\x12%\n" +
	"\x02vm\x18\x01 \x01(\v2\x15.sandboxgateway.VMRefR\x02vm\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x16\n" +
	"\x06append\x18\x04 \x01(\bR\x06append\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\x05R\x04mode\"8\n" +
	"\x11WriteFileResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\"K\n" +
	"\x0eListDirRequest\x12%\n" +
	"\x02vm\x18\x01 \x01(\v2\x15.sandboxgateway.VMRefR\x02vm\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"K\n" +
	"\x0fListDirResponse\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.sandboxgateway.GuestFileEntryR\aentries\"t\n" +
	"\x0eGuestFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\x12#\n" +
	"\rmodified_unix\x18\x04 \x01(\x03R\fmodifiedUnix\"H\n" +
	"\vStatRequest\x12%\n" +
	"\x02vm\x18\x01 \x01(\v2\x15.sandboxgateway.VMRefR\x02vm\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"r\n" +
	"\fStatResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12#\n" +
	"\rmodified_unix\x18\x03 \x01(\x03R\fmodifiedUnix\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\x05R\x04mode\"h\n" +
	"\rRemoveRequest\x12%\n" +
	"\x02vm\x18\x01 \x01(\v2\x15.sandboxgateway.VMRefR\x02vm\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x03 \x01(\bR\trecursive\"\x10\n" +
	"\x0eRemoveResponse2\xcb\x03\n" +
	"\x0eSandboxGateway\x12@\n" +
	"\x04Exec\x12\x1b.sandboxgateway.ExecRequest\x1a\x19.sandboxgateway.ExecFrame0\x01\x12M\n" +
	"\bReadFile\x12\x1f.sandboxgateway.ReadFileRequest\x1a .sandboxgateway.ReadFileResponse\x12P\n" +
	"\tWriteFile\x12 .sandboxgateway.WriteFileRequest\x1a!.sandboxgateway.WriteFileResponse\x12J\n" +
	"\aListDir\x12\x1e.sandboxgateway.ListDirRequest\x1a\x1f.sandboxgateway.ListDirResponse\x12A\n" +
	"\x04Stat\x12\x1b.sandboxgateway.StatRequest\x1a\x1c.sandboxgateway.StatResponse\x12G\n" +
	"\x06Remove\x12\x1d.sandboxgateway.RemoveRequest\x1a\x1e.sandboxgateway.RemoveResponseB\xa6\x01\n" +
	"\x12com.sandboxgatewayB\fGatewayProtoP\x01Z*github.com/syscode-labs/imp/sandboxgateway\xa2\x02\x03SXX\xaa\x02\x0eSandboxgateway\xca\x02\x0eSandboxgateway\xe2\x02\x1aSandboxgateway\\GPBMetadata\xea\x02\x0eSandboxgatewayb\x06proto3"

var (
	file_sandboxgateway_gateway_proto_rawDescOnce sync.Once
	file_sandboxgateway_gateway_proto_rawDescData []byte
)

func file_sandboxgateway_gateway_proto_rawDescGZIP() []byte {
	file_sandboxgateway_gateway_proto_rawDescOnce.Do(func() {
		file_sandboxgateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandboxgateway_gateway_proto_rawDesc), len(file_sandboxgateway_gateway_proto_rawDesc)))
	})
	return file_sandboxgateway_gateway_proto_rawDescData
}

var file_sandboxgateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_sandboxgateway_gateway_proto_goTypes = []any{
	(*VMRef)(nil),             // 0: sandboxgateway.VMRef
	(*ExecRequest)(nil),       // 1: sandboxgateway.ExecRequest
	(*ExecFrame)(nil),         // 2: sandboxgateway.ExecFrame
	(*ReadFileRequest)(nil),   // 3: sandboxgateway.ReadFileRequest
	(*ReadFileResponse)(nil),  // 4: sandboxgateway.ReadFileResponse
	(*WriteFileRequest)(nil),  // 5: sandboxgateway.WriteFileRequest
	(*WriteFileResponse)(nil), // 6: sandboxgateway.WriteFileResponse
	(*ListDirRequest)(nil),    // 7: sandboxgateway.ListDirRequest
	(*ListDirResponse)(nil),   // 8: sandboxgateway.ListDirResponse
	(*GuestFileEntry)(nil),    // 9: sandboxgateway.GuestFileEntry
	(*StatRequest)(nil),       // 10: sandboxgateway.StatRequest
	(*StatResponse)(nil),      // 11: sandboxgateway.StatResponse
	(*RemoveRequest)(nil),     // 12: sandboxgateway.RemoveRequest
	(*RemoveResponse)(nil),    // 13: sandboxgateway.RemoveResponse
}
var file_sandboxgateway_gateway_proto_depIdxs = []int32{
	0,  // 0: sandboxgateway.ExecRequest.vm:type_name -> sandboxgateway.VMRef
	0,  // 1: sandboxgateway.ReadFileRequest.vm:type_name -> sandboxgateway.VMRef
	0,  // 2: sandboxgateway.WriteFileRequest.vm:type_name -> sandboxgateway.VMRef
	0,  // 3: sandboxgateway.ListDirRequest.vm:type_name -> sandboxgateway.VMRef
	9,  // 4: sandboxgateway.ListDirResponse.entries:type_name -> sandboxgateway.GuestFileEntry
	0,  // 5: sandboxgateway.StatRequest.vm:type_name -> sandboxgateway.VMRef
	0,  // 6: sandboxgateway.RemoveRequest.vm:type_name -> sandboxgateway.VMRef
	1,  // 7: sandboxgateway.SandboxGateway.Exec:input_type -> sandboxgateway.ExecRequest
	3,  // 8: sandboxgateway.SandboxGateway.ReadFile:input_type -> sandboxgateway.ReadFileRequest
	5,  // 9: sandboxgateway.SandboxGateway.WriteFile:input_type -> sandboxgateway.WriteFileRequest
	7,  // 10: sandboxgateway.SandboxGateway.ListDir:input_type -> sandboxgateway.ListDirRequest
	10, // 11: sandboxgateway.SandboxGateway.Stat:input_type -> sandboxgateway.StatRequest
	12, // 12: sandboxgateway.SandboxGateway.Remove:input_type -> sandboxgateway.RemoveRequest
	2,  // 13: sandboxgateway.SandboxGateway.Exec:output_type -> sandboxgateway.ExecFrame
	4,  // 14: sandboxgateway.SandboxGateway.ReadFile:output_type -> sandboxgateway.ReadFileResponse
	6,  // 15: sandboxgateway.SandboxGateway.WriteFile:output_type -> sandboxgateway.WriteFileResponse
	8,  // 16: sandboxgateway.SandboxGateway.ListDir:output_type -> sandboxgateway.ListDirResponse
	11, // 17: sandboxgateway.SandboxGateway.Stat:output_type -> sandboxgateway.StatResponse
	13, // 18: sandboxgateway.SandboxGateway.Remove:output_type -> sandboxgateway.RemoveResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_sandboxgateway_gateway_proto_init() }
func file_sandboxgateway_gateway_proto_init() {
	if File_sandboxgateway_gateway_proto != nil {
		return
	}
	file_sandboxgateway_gateway_proto_msgTypes[2].OneofWrappers = []any{
		(*ExecFrame_Stdout)(nil),
		(*ExecFrame_Stderr)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandboxgateway_gateway_proto_rawDesc), len(file_sandboxgateway_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandboxgateway_gateway_proto_goTypes,
		DependencyIndexes: file_sandboxgateway_gateway_proto_depIdxs,
		MessageInfos:      file_sandboxgateway_gateway_proto_msgTypes,
	}.Build()
	File_sandboxgateway_gateway_proto = out.File
	file_sandboxgateway_gateway_proto_goTypes = nil
	file_sandboxgateway_gateway_proto_depIdxs = nil
}
