// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: sandboxgateway/gateway.proto

// Package sandboxgateway defines the node-local data-plane gateway service.
// The gateway authenticates callers via per-sandbox HMAC bearer tokens and
// proxies calls to the guest SandboxControl service over the VM's VSOCK
// unix socket.

package sandboxgateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxGateway_Exec_FullMethodName      = "/sandboxgateway.SandboxGateway/Exec"
	SandboxGateway_ReadFile_FullMethodName  = "/sandboxgateway.SandboxGateway/ReadFile"
	SandboxGateway_WriteFile_FullMethodName = "/sandboxgateway.SandboxGateway/WriteFile"
	SandboxGateway_ListDir_FullMethodName   = "/sandboxgateway.SandboxGateway/ListDir"
	SandboxGateway_Stat_FullMethodName      = "/sandboxgateway.SandboxGateway/Stat"
	SandboxGateway_Remove_FullMethodName    = "/sandboxgateway.SandboxGateway/Remove"
)

// SandboxGatewayClient is the client API for SandboxGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SandboxGatewayClient interface {
	// Exec runs a command in the sandbox and streams output frames.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecFrame], error)
	// ReadFile returns up to 1 MiB of a file inside the sandbox.
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	// WriteFile writes up to 1 MiB to a file inside the sandbox.
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	// ListDir lists one directory level inside the sandbox.
	ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error)
	// Stat returns metadata for a path inside the sandbox.
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	// Remove deletes a file or empty directory inside the sandbox.
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
}

type sandboxGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxGatewayClient(cc grpc.ClientConnInterface) SandboxGatewayClient {
	return &sandboxGatewayClient{cc}
}

func (c *sandboxGatewayClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxGateway_ServiceDesc.Streams[0], SandboxGateway_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxGateway_ExecClient = grpc.ServerStreamingClient[ExecFrame]

func (c *sandboxGatewayClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, SandboxGateway_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxGatewayClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, SandboxGateway_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxGatewayClient) ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirResponse)
	err := c.cc.Invoke(ctx, SandboxGateway_ListDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxGatewayClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, SandboxGateway_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxGatewayClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, SandboxGateway_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxGatewayServer is the server API for SandboxGateway service.
// All implementations must embed UnimplementedSandboxGatewayServer
// for forward compatibility.
type SandboxGatewayServer interface {
	// Exec runs a command in the sandbox and streams output frames.
	Exec(*ExecRequest, grpc.ServerStreamingServer[ExecFrame]) error
	// ReadFile returns up to 1 MiB of a file inside the sandbox.
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	// WriteFile writes up to 1 MiB to a file inside the sandbox.
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	// ListDir lists one directory level inside the sandbox.
	ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error)
	// Stat returns metadata for a path inside the sandbox.
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	// Remove deletes a file or empty directory inside the sandbox.
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	mustEmbedUnimplementedSandboxGatewayServer()
}

// UnimplementedSandboxGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxGatewayServer struct{}

func (UnimplementedSandboxGatewayServer) Exec(*ExecRequest, grpc.ServerStreamingServer[ExecFrame]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedSandboxGatewayServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedSandboxGatewayServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedSandboxGatewayServer) ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDir not implemented")
}
func (UnimplementedSandboxGatewayServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedSandboxGatewayServer) Remove(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedSandboxGatewayServer) mustEmbedUnimplementedSandboxGatewayServer() {}
func (UnimplementedSandboxGatewayServer) testEmbeddedByValue()                        {}

// UnsafeSandboxGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxGatewayServer will
// result in compilation errors.
type UnsafeSandboxGatewayServer interface {
	mustEmbedUnimplementedSandboxGatewayServer()
}

func RegisterSandboxGatewayServer(s grpc.ServiceRegistrar, srv SandboxGatewayServer) {
	// If the following call panics, it indicates UnimplementedSandboxGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxGateway_ServiceDesc, srv)
}

func _SandboxGateway_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxGatewayServer).Exec(m, &grpc.GenericServerStream[ExecRequest, ExecFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxGateway_ExecServer = grpc.ServerStreamingServer[ExecFrame]

func _SandboxGateway_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxGatewayServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxGateway_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxGatewayServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxGateway_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxGatewayServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxGateway_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxGatewayServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxGateway_ListDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxGatewayServer).ListDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxGateway_ListDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxGatewayServer).ListDir(ctx, req.(*ListDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxGateway_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxGatewayServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxGateway_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxGatewayServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxGateway_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxGatewayServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxGateway_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxGatewayServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxGateway_ServiceDesc is the grpc.ServiceDesc for SandboxGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandboxgateway.SandboxGateway",
	HandlerType: (*SandboxGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadFile",
			Handler:    _SandboxGateway_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _SandboxGateway_WriteFile_Handler,
		},
		{
			MethodName: "ListDir",
			Handler:    _SandboxGateway_ListDir_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _SandboxGateway_Stat_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _SandboxGateway_Remove_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _SandboxGateway_Exec_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sandboxgateway/gateway.proto",
}
