// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: sandbox/sandbox.proto

// Package sandbox defines the control-session RPC surface used by the optional
// Imp Sandbox add-on. It is compiled into the guest agent but remains inert
// unless a session is opened with the configured control token.

package sandbox

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxControl_OpenSession_FullMethodName  = "/sandbox.SandboxControl/OpenSession"
	SandboxControl_CloseSession_FullMethodName = "/sandbox.SandboxControl/CloseSession"
	SandboxControl_Exec_FullMethodName         = "/sandbox.SandboxControl/Exec"
)

// SandboxControlClient is the client API for SandboxControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SandboxControlClient interface {
	// OpenSession exchanges a one-time control token for a session handle.
	OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error)
	// CloseSession invalidates a previously opened session handle.
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
	// Exec runs a command inside the VM within an open session.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
}

type sandboxControlClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxControlClient(cc grpc.ClientConnInterface) SandboxControlClient {
	return &sandboxControlClient{cc}
}

func (c *sandboxControlClient) OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenSessionResponse)
	err := c.cc.Invoke(ctx, SandboxControl_OpenSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxControlClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseSessionResponse)
	err := c.cc.Invoke(ctx, SandboxControl_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxControlClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, SandboxControl_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxControlServer is the server API for SandboxControl service.
// All implementations must embed UnimplementedSandboxControlServer
// for forward compatibility.
type SandboxControlServer interface {
	// OpenSession exchanges a one-time control token for a session handle.
	OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error)
	// CloseSession invalidates a previously opened session handle.
	CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error)
	// Exec runs a command inside the VM within an open session.
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	mustEmbedUnimplementedSandboxControlServer()
}

// UnimplementedSandboxControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxControlServer struct{}

func (UnimplementedSandboxControlServer) OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedSandboxControlServer) CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedSandboxControlServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedSandboxControlServer) mustEmbedUnimplementedSandboxControlServer() {}
func (UnimplementedSandboxControlServer) testEmbeddedByValue()                        {}

// UnsafeSandboxControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxControlServer will
// result in compilation errors.
type UnsafeSandboxControlServer interface {
	mustEmbedUnimplementedSandboxControlServer()
}

func RegisterSandboxControlServer(s grpc.ServiceRegistrar, srv SandboxControlServer) {
	// If the following call panics, it indicates UnimplementedSandboxControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxControl_ServiceDesc, srv)
}

func _SandboxControl_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).OpenSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_OpenSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).OpenSession(ctx, req.(*OpenSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxControl_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxControl_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxControl_ServiceDesc is the grpc.ServiceDesc for SandboxControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.SandboxControl",
	HandlerType: (*SandboxControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenSession",
			Handler:    _SandboxControl_OpenSession_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _SandboxControl_CloseSession_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _SandboxControl_Exec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sandbox/sandbox.proto",
}
