// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sandbox/sandbox.proto

// Package sandbox defines the control-session RPC surface used by the optional
// Imp Sandbox add-on. It is compiled into the guest agent but remains inert
// unless a session is opened with the configured control token.

package sandbox

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_sandbox_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *OpenSessionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type OpenSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionResponse) Reset() {
	*x = OpenSessionResponse{}
	mi := &file_sandbox_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionResponse) ProtoMessage() {}

func (x *OpenSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionResponse.ProtoReflect.Descriptor instead.
func (*OpenSessionResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *OpenSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_sandbox_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_sandbox_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_sandbox_proto_rawDescGZIP(), []int{3}
}

type ExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command        []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_sandbox_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *ExecRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_sandbox_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

var File_sandbox_sandbox_proto protoreflect.FileDescriptor

const file_sandbox_sandbox_proto_rawDesc = "" +
	"\n" +
	"\x15sandbox/sandbox.proto\x12\asandbox\"*\n" +
	"\x12OpenSessionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"4\n" +
	"\x13OpenSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x16\n" +
	"\x14CloseSessionResponse\"o\n" +
	"\vExecRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"[\n" +
	"\fExecResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr2\xdc\x01\n" +
	"\x0eSandboxControl\x12H\n" +
	"\vOpenSession\x12\x1b.sandbox.OpenSessionRequest\x1a\x1c.sandbox.OpenSessionResponse\x12K\n" +
	"\fCloseSession\x12\x1c.sandbox.CloseSessionRequest\x1a\x1d.sandbox.CloseSessionResponse\x123\n" +
	"\x04Exec\x12\x14.sandbox.ExecRequest\x1a\x15.sandbox.ExecResponseB|\n" +
	"\vcom.sandboxB\fSandboxProtoP\x01Z#github.com/syscode-labs/imp/sandbox\xa2\x02\x03SXX\xaa\x02\aSandbox\xca\x02\aSandbox\xe2\x02\x13Sandbox\\GPBMetadata\xea\x02\aSandboxb\x06proto3"

var (
	file_sandbox_sandbox_proto_rawDescOnce sync.Once
	file_sandbox_sandbox_proto_rawDescData []byte
)

func file_sandbox_sandbox_proto_rawDescGZIP() []byte {
	file_sandbox_sandbox_proto_rawDescOnce.Do(func() {
		file_sandbox_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_sandbox_proto_rawDesc), len(file_sandbox_sandbox_proto_rawDesc)))
	})
	return file_sandbox_sandbox_proto_rawDescData
}

var file_sandbox_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sandbox_sandbox_proto_goTypes = []any{
	(*OpenSessionRequest)(nil),   // 0: sandbox.OpenSessionRequest
	(*OpenSessionResponse)(nil),  // 1: sandbox.OpenSessionResponse
	(*CloseSessionRequest)(nil),  // 2: sandbox.CloseSessionRequest
	(*CloseSessionResponse)(nil), // 3: sandbox.CloseSessionResponse
	(*ExecRequest)(nil),          // 4: sandbox.ExecRequest
	(*ExecResponse)(nil),         // 5: sandbox.ExecResponse
}
var file_sandbox_sandbox_proto_depIdxs = []int32{
	0, // 0: sandbox.SandboxControl.OpenSession:input_type -> sandbox.OpenSessionRequest
	2, // 1: sandbox.SandboxControl.CloseSession:input_type -> sandbox.CloseSessionRequest
	4, // 2: sandbox.SandboxControl.Exec:input_type -> sandbox.ExecRequest
	1, // 3: sandbox.SandboxControl.OpenSession:output_type -> sandbox.OpenSessionResponse
	3, // 4: sandbox.SandboxControl.CloseSession:output_type -> sandbox.CloseSessionResponse
	5, // 5: sandbox.SandboxControl.Exec:output_type -> sandbox.ExecResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sandbox_sandbox_proto_init() }
func file_sandbox_sandbox_proto_init() {
	if File_sandbox_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_sandbox_proto_rawDesc), len(file_sandbox_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_sandbox_proto_goTypes,
		DependencyIndexes: file_sandbox_sandbox_proto_depIdxs,
		MessageInfos:      file_sandbox_sandbox_proto_msgTypes,
	}.Build()
	File_sandbox_sandbox_proto = out.File
	file_sandbox_sandbox_proto_goTypes = nil
	file_sandbox_sandbox_proto_depIdxs = nil
}
