apiVersion: imp.dev/v1alpha1
kind: ImpVM
metadata:
  name: team-b-app
  namespace: team-b
spec:
  classRef:
    name: team-b-class
  networkRef:
    name: team-b-net
  image: ghcr.io/syscode-labs/test:latest
  lifecycle: persistent
