name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Commit message convention check
        if: ${{ !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'dependabot/')) }}
        run: |
          python -m pip install --upgrade pip commitizen
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            RANGE="${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
          else
            RANGE="${{ github.event.before }}..${{ github.sha }}"
          fi
          echo "Checking commit messages in range: ${RANGE}"
          cz check --rev-range "${RANGE}"

      - name: Check linter configuration
        run: make lint-config
      - name: Run linter
        run: make lint
